USE CPJudge;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'Users')
BEGIN
    CREATE TABLE Users (
        ID INT PRIMARY KEY,
        userName VARCHAR(100) NOT NULL,
        email VARCHAR(100),
        rating INT NOT NULL
    )
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Problems')
BEGIN
    CREATE TABLE Problems (
        ID INT PRIMARY KEY,
        statement VARCHAR(200)
    )
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'IODate')
BEGIN
    CREATE TABLE IODate (
        ID INT PRIMARY KEY,
        problemID INT FOREIGN KEY REFERENCES Problems(ID),
        inputData VARCHAR(100) NOT NULL,
        outputData VARCHAR(100) NOT NULL,
        isSample BIT NOT NULL
    )
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'StatusCode')
BEGIN
    CREATE TABLE StatusCode (
        ID INT PRIMARY KEY,
        code VARCHAR(5) NOT NULL,
        description VARCHAR(100) NOT NULL
    )
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Solutions')
BEGIN
    CREATE TABLE Solutions (
        ID INT PRIMARY KEY,
        userID INT FOREIGN KEY REFERENCES Users(ID),
        problemID INT FOREIGN KEY REFERENCES Problems(ID),
        code VARCHAR(100) NOT NULL,
        status INT FOREIGN KEY REFERENCES StatusCode(ID)
    )
END

GO
